# Generated by Django 5.1.1 on 2024-09-08 08:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookdetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
